[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION               = "18"
  NPM_CONFIG_BUILD_FROM_SOURCE = "true"
  NPM_CONFIG_PREBUILD_INSTALL  = "false"
