
[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_ENV = "production"
  npm_config_arch = "x64"
  npm_config_platform = "linux"
  npm_config_libc = "glibc"
  npm_config_build_from_source = "true"
